spring.application.name=demo
# Server Port
server.port=8000

# SQLite Datasource
spring.datasource.url=jdbc:sqlite:./data/main.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# JPA Properties
spring.jpa.hibernate.ddl-auto=create

## more advanced persistence

# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# spring.h2.console.enabled=true